// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ExtramuralEducation.WebSite.Controllers.Admin
{
    public partial class AdminUserController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminUserController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditUsersInstitutions()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUsersInstitutions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminUserController Actions { get { return MVC.AdminUser; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AdminUser";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AdminUser";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string AddUser = "AddUser";
            public readonly string EditUsersInstitutions = "EditUsersInstitutions";
            public readonly string DeleteUser = "DeleteUser";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string AddUser = "AddUser";
            public const string EditUsersInstitutions = "EditUsersInstitutions";
            public const string DeleteUser = "DeleteUser";
        }


        static readonly ActionParamsClass_AddUser s_params_AddUser = new ActionParamsClass_AddUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddUser AddUserParams { get { return s_params_AddUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddUser
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_EditUsersInstitutions s_params_EditUsersInstitutions = new ActionParamsClass_EditUsersInstitutions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditUsersInstitutions EditUsersInstitutionsParams { get { return s_params_EditUsersInstitutions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditUsersInstitutions
        {
            public readonly string userName = "userName";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_DeleteUser s_params_DeleteUser = new ActionParamsClass_DeleteUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUser DeleteUserParams { get { return s_params_DeleteUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUser
        {
            public readonly string userName = "userName";
            public readonly string Id = "Id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
            }
            public readonly string Index = "~/Views/AdminUser/Index.cshtml";
            static readonly _PartialClass s_Partial = new _PartialClass();
            public _PartialClass Partial { get { return s_Partial; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _PartialClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string DeleteUser = "DeleteUser";
                    public readonly string UserFields = "UserFields";
                    public readonly string UserInstitutions = "UserInstitutions";
                }
                public readonly string DeleteUser = "~/Views/AdminUser/Partial/DeleteUser.cshtml";
                public readonly string UserFields = "~/Views/AdminUser/Partial/UserFields.cshtml";
                public readonly string UserInstitutions = "~/Views/AdminUser/Partial/UserInstitutions.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AdminUserController : ExtramuralEducation.WebSite.Controllers.Admin.AdminUserController
    {
        public T4MVC_AdminUserController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void AddUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult AddUser()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUser);
            AddUserOverride(callInfo);
            return callInfo;
        }

        partial void AddUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ExtramuralEducation.ViewModels.UserViewModel viewModel);

        public override System.Web.Mvc.ActionResult AddUser(ExtramuralEducation.ViewModels.UserViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            AddUserOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void EditUsersInstitutionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string userName);

        public override System.Web.Mvc.ActionResult EditUsersInstitutions(string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUsersInstitutions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            EditUsersInstitutionsOverride(callInfo, userName);
            return callInfo;
        }

        partial void EditUsersInstitutionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ExtramuralEducation.ViewModels.UserInstitutionsViewModel viewModel);

        public override System.Web.Mvc.ActionResult EditUsersInstitutions(ExtramuralEducation.ViewModels.UserInstitutionsViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUsersInstitutions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            EditUsersInstitutionsOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void DeleteUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string userName);

        public override System.Web.Mvc.ActionResult DeleteUser(string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            DeleteUserOverride(callInfo, userName);
            return callInfo;
        }

        partial void DeleteUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid Id);

        public override System.Web.Mvc.ActionResult DeleteUser(System.Guid Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteUserOverride(callInfo, Id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
